package edu.mit.moira.internal;

import java.util.Hashtable;

public class MoiraET {
	private static Hashtable<Integer, String> errMsgList;

	public static String getErrorMessage(long i) {
	    return errMsgList.get(i);
	}
	
	public static final int MR_NOT_CONNECTED = 47836416;
	public static final int MR_CANT_CONNECT = 47836417;
	public static final int MR_VERSION_MISMATCH = 47836418;
	public static final int MR_ABORTED = 47836419;
	public static final int MR_UNKNOWN_PROC = 47836420;
	public static final int MR_DBMS_ERR = 47836421;
	public static final int MR_MORE_DATA = 47836422;
	public static final int MR_NO_MATCH = 47836423;
	public static final int MR_NO_HANDLE = 47836424;
	public static final int MR_ALREADY_CONNECTED = 47836425;
	public static final int MR_ARGS = 47836426;
	public static final int MR_NOT_UNIQUE = 47836427;
	public static final int MR_PERM = 47836428;
	public static final int MR_LIST = 47836429;
	public static final int MR_USER = 47836430;
	public static final int MR_STRING = 47836431;
	public static final int MR_TYPE = 47836432;
	public static final int MR_EXISTS = 47836433;
	public static final int MR_DATE = 47836434;
	public static final int MR_CLUSTER = 47836435;
	public static final int MR_MACHINE = 47836436;
	public static final int MR_SERVICE = 47836437;
	public static final int MR_FILESYS = 47836438;
	public static final int MR_PRINTER = 47836439;
	public static final int MR_QUEUE = 47836440;
	public static final int MR_DEVICE = 47836441;
	public static final int MR_ACE = 47836442;
	public static final int MR_NFSPHYS = 47836443;
	public static final int MR_FILESYS_EXISTS = 47836444;
	public static final int MR_QUERY_NOT_REENTRANT = 47836445;
	public static final int MR_RVD = 47836446;
	public static final int MR_NFS = 47836447;
	public static final int MR_FILESYS_ACCESS = 47836448;
	public static final int MR_USER_GROUP = 47836449;
	public static final int MR_ARG_TOO_LONG = 47836450;
	public static final int MR_NO_MEM = 47836451;
	public static final int MR_IN_USE = 47836452;
	public static final int MR_BAD_CLASS = 47836453;
	public static final int MR_INTERNAL = 47836454;
	public static final int MR_BAD_CHAR = 47836455;
	public static final int MR_BAD_GROUP = 47836456;
	public static final int MR_WILDCARD = 47836457;
	public static final int MR_NO_CHANGE = 47836458;
	public static final int MR_TAR_FAIL = 47836459;
	public static final int MR_OCONFIG = 47836460;
	public static final int MR_CCONFIG = 47836461;
	public static final int MR_FSTYPE = 47836462;
	public static final int MR_INTEGER = 47836463;
	public static final int MR_NO_ID = 47836464;
	public static final int MR_NO_FILESYS = 47836465;
	public static final int MR_NO_POBOX = 47836466;
	public static final int MR_NO_QUOTA = 47836467;
	public static final int MR_USER_AUTH = 47836468;
	public static final int MR_DEADLOCK = 47836469;
	public static final int MR_NOCRED = 47836470;
	public static final int MR_SETQUOTA = 47836471;
	public static final int MR_HESFILE = 47836472;
	public static final int MR_MISSINGFILE = 47836473;
	public static final int MR_MKCRED = 47836474;
	public static final int MR_NAMED = 47836475;
	public static final int MR_TARERR = 47836476;
	public static final int MR_PROTO = 47836477;
	public static final int MR_BUSY = 47836478;
	public static final int MR_DOWN = 47836479;
	public static final int MR_LISTLOOP = 47836480;
	public static final int MR_DBMS_SOFTFAIL = 47836481;
	public static final int MR_COREDUMP = 47836482;
	public static final int MR_SUBNET = 47836483;
	public static final int MR_ADDRESS = 47836484;
	public static final int MR_VERSION_LOW = 47836485;
	public static final int MR_VERSION_HIGH = 47836486;
	public static final int MR_RESERVED = 47836487;
	public static final int MR_QUALITY = 47836488;
	public static final int MR_CONTAINER = 47836489;
	public static final int MR_NEW_CONTAINER_NAME = 47836490;
	public static final int MR_ACCOUNT_NUMBER = 47836491;
	public static final int MR_CONTAINER_NO_PARENT = 47836492;
	public static final int MR_BAD_MAIL_STRING = 47836493;
	public static final int MR_NO_KRB4 = 47836494;
	
	static {
		errMsgList = new Hashtable<Integer, String>();
		errMsgList.put(MR_NOT_CONNECTED, "Not connected to Moira server");
		errMsgList.put(MR_CANT_CONNECT, "Can't connect to Moira server");
		errMsgList.put(MR_VERSION_MISMATCH, "Moira version mismatch");
		errMsgList.put(MR_ABORTED, "Moira operation aborted");
		errMsgList.put(MR_UNKNOWN_PROC, "Unknown procedure");
		errMsgList.put(MR_DBMS_ERR, "DBMS system error occurred");
		errMsgList.put(MR_MORE_DATA, "More data is available from Moira");
		errMsgList.put(MR_NO_MATCH, "No records in database match query");
		errMsgList.put(MR_NO_HANDLE, "Unknown query handle");
		errMsgList.put(MR_ALREADY_CONNECTED, "Already connected to the moira server");
		errMsgList.put(MR_ARGS, "Incorrect number of arguments");
		errMsgList.put(MR_NOT_UNIQUE, "Arguments not unique");
		errMsgList.put(MR_PERM, "Insufficient permission to perform requested database access");
		errMsgList.put(MR_LIST, "No such list");
		errMsgList.put(MR_USER, "No such user");
		errMsgList.put(MR_STRING, "Unknown string");
		errMsgList.put(MR_TYPE, "Invalid type");
		errMsgList.put(MR_EXISTS, "Record already exists");
		errMsgList.put(MR_DATE, "Invalid date");
		errMsgList.put(MR_CLUSTER, "Unknown cluster");
		errMsgList.put(MR_MACHINE, "Unknown machine");
		errMsgList.put(MR_SERVICE, "Unknown service");
		errMsgList.put(MR_FILESYS, "Named file system does not exist");
		errMsgList.put(MR_PRINTER, "Unknown printer");
		errMsgList.put(MR_QUEUE, "Unknown queue");
		errMsgList.put(MR_DEVICE, "No such device");
		errMsgList.put(MR_ACE, "No such access control entity");
		errMsgList.put(MR_NFSPHYS, "Machine/device pair not in nfsphys");
		errMsgList.put(MR_FILESYS_EXISTS, "Named file system already exists");
		errMsgList.put(MR_QUERY_NOT_REENTRANT, "Cannot do query from callback routine");
		errMsgList.put(MR_RVD, "No such rvd");
		errMsgList.put(MR_NFS, "Specified directory not exported");
		errMsgList.put(MR_FILESYS_ACCESS, "Invalid filesys access");
		errMsgList.put(MR_USER_GROUP, "List is a user group");
		errMsgList.put(MR_ARG_TOO_LONG, "An argument is too long");
		errMsgList.put(MR_NO_MEM, "Server ran out of memory");
		errMsgList.put(MR_IN_USE, "Object is in use");
		errMsgList.put(MR_BAD_CLASS, "Specified class is not known");
		errMsgList.put(MR_INTERNAL, "Moira internal consistency failure");
		errMsgList.put(MR_BAD_CHAR, "Illegal character in argument");
		errMsgList.put(MR_BAD_GROUP, "Invalid group ID");
		errMsgList.put(MR_WILDCARD, "Wildcards not allowed in this case");
		errMsgList.put(MR_NO_CHANGE, "The database has not changed, files not rebuilt");
		errMsgList.put(MR_TAR_FAIL, "Unable to build archive of config files");
		errMsgList.put(MR_OCONFIG, "Unable to open DCM file");
		errMsgList.put(MR_CCONFIG, "Error closing DCM output file");
		errMsgList.put(MR_FSTYPE, "Unknown filesys type");
		errMsgList.put(MR_INTEGER, "String could not be parsed as an integer");
		errMsgList.put(MR_NO_ID, "Cannot allocate new ID");
		errMsgList.put(MR_NO_FILESYS, "Cannot find space for filesys");
		errMsgList.put(MR_NO_POBOX, "Cannot find space for pobox");
		errMsgList.put(MR_NO_QUOTA, "No default quota specified");
		errMsgList.put(MR_USER_AUTH, "Cannot find you in the database, access will be restricted");
		errMsgList.put(MR_DEADLOCK, "Database deadlock; try again later");
		errMsgList.put(MR_NOCRED, "Unable to install new credentials files");
		errMsgList.put(MR_SETQUOTA, "Failure setting user quota");
		errMsgList.put(MR_HESFILE, "Unable to copy hesiod file into nameserver directory");
		errMsgList.put(MR_MISSINGFILE, "Did not receive file for update");
		errMsgList.put(MR_MKCRED, "unable to compile database files");
		errMsgList.put(MR_NAMED, "name daemon failed to start");
		errMsgList.put(MR_TARERR, "Unable to extract DCM files");
		errMsgList.put(MR_PROTO, "Failed to put prototype files in new locker");
		errMsgList.put(MR_BUSY, "the database is busy; try again later");
		errMsgList.put(MR_DOWN, "the database is closed right now; try again later");
		errMsgList.put(MR_LISTLOOP, "Lists are not allowed to contain themselves as members");
		errMsgList.put(MR_DBMS_SOFTFAIL, "Temporary database failure, try again");
		errMsgList.put(MR_COREDUMP, "Subprocess coredumped");
		errMsgList.put(MR_SUBNET, "Bad subnet");
		errMsgList.put(MR_ADDRESS, "Bad address");
		errMsgList.put(MR_VERSION_LOW, "Client query version is older than server");
		errMsgList.put(MR_VERSION_HIGH, "Client query version is newer than server");
		errMsgList.put(MR_RESERVED, "That name is reserved");
		errMsgList.put(MR_QUALITY, "Password is too simple");
		errMsgList.put(MR_CONTAINER, "No such container");
		errMsgList.put(MR_NEW_CONTAINER_NAME, "The new container name is invalid");
		errMsgList.put(MR_ACCOUNT_NUMBER, "No such account number");
		errMsgList.put(MR_CONTAINER_NO_PARENT, "Parent container does not exist");
		errMsgList.put(MR_BAD_MAIL_STRING, "Address refers to nonexistent domain or MIT internal mail server");
		errMsgList.put(MR_NO_KRB4, "Unable to complete operation using Kerberos v4");
	}
}
