package mit.moira.internal;

import java.util.Hashtable;

public class MoiraET {
	private static Hashtable<Long, String> errMsgList;

	public static String getErrorMessage(long i) {
	    return errMsgList.get(i);
	}
	
	public static final long MR_NOT_CONNECTED = 47836416L;
	public static final long MR_CANT_CONNECT = 47836417L;
	public static final long MR_VERSION_MISMATCH = 47836418L;
	public static final long MR_ABORTED = 47836419L;
	public static final long MR_UNKNOWN_PROC = 47836420L;
	public static final long MR_DBMS_ERR = 47836421L;
	public static final long MR_MORE_DATA = 47836422L;
	public static final long MR_NO_MATCH = 47836423L;
	public static final long MR_NO_HANDLE = 47836424L;
	public static final long MR_ALREADY_CONNECTED = 47836425L;
	public static final long MR_ARGS = 47836426L;
	public static final long MR_NOT_UNIQUE = 47836427L;
	public static final long MR_PERM = 47836428L;
	public static final long MR_LIST = 47836429L;
	public static final long MR_USER = 47836430L;
	public static final long MR_STRING = 47836431L;
	public static final long MR_TYPE = 47836432L;
	public static final long MR_EXISTS = 47836433L;
	public static final long MR_DATE = 47836434L;
	public static final long MR_CLUSTER = 47836435L;
	public static final long MR_MACHINE = 47836436L;
	public static final long MR_SERVICE = 47836437L;
	public static final long MR_FILESYS = 47836438L;
	public static final long MR_PRINTER = 47836439L;
	public static final long MR_QUEUE = 47836440L;
	public static final long MR_DEVICE = 47836441L;
	public static final long MR_ACE = 47836442L;
	public static final long MR_NFSPHYS = 47836443L;
	public static final long MR_FILESYS_EXISTS = 47836444L;
	public static final long MR_QUERY_NOT_REENTRANT = 47836445L;
	public static final long MR_RVD = 47836446L;
	public static final long MR_NFS = 47836447L;
	public static final long MR_FILESYS_ACCESS = 47836448L;
	public static final long MR_USER_GROUP = 47836449L;
	public static final long MR_ARG_TOO_LONG = 47836450L;
	public static final long MR_NO_MEM = 47836451L;
	public static final long MR_IN_USE = 47836452L;
	public static final long MR_BAD_CLASS = 47836453L;
	public static final long MR_INTERNAL = 47836454L;
	public static final long MR_BAD_CHAR = 47836455L;
	public static final long MR_BAD_GROUP = 47836456L;
	public static final long MR_WILDCARD = 47836457L;
	public static final long MR_NO_CHANGE = 47836458L;
	public static final long MR_TAR_FAIL = 47836459L;
	public static final long MR_OCONFIG = 47836460L;
	public static final long MR_CCONFIG = 47836461L;
	public static final long MR_FSTYPE = 47836462L;
	public static final long MR_INTEGER = 47836463L;
	public static final long MR_NO_ID = 47836464L;
	public static final long MR_NO_FILESYS = 47836465L;
	public static final long MR_NO_POBOX = 47836466L;
	public static final long MR_NO_QUOTA = 47836467L;
	public static final long MR_USER_AUTH = 47836468L;
	public static final long MR_DEADLOCK = 47836469L;
	public static final long MR_NOCRED = 47836470L;
	public static final long MR_SETQUOTA = 47836471L;
	public static final long MR_HESFILE = 47836472L;
	public static final long MR_MISSINGFILE = 47836473L;
	public static final long MR_MKCRED = 47836474L;
	public static final long MR_NAMED = 47836475L;
	public static final long MR_TARERR = 47836476L;
	public static final long MR_PROTO = 47836477L;
	public static final long MR_BUSY = 47836478L;
	public static final long MR_DOWN = 47836479L;
	public static final long MR_LISTLOOP = 47836480L;
	public static final long MR_DBMS_SOFTFAIL = 47836481L;
	public static final long MR_COREDUMP = 47836482L;
	public static final long MR_SUBNET = 47836483L;
	public static final long MR_ADDRESS = 47836484L;
	public static final long MR_VERSION_LOW = 47836485L;
	public static final long MR_VERSION_HIGH = 47836486L;
	public static final long MR_RESERVED = 47836487L;
	public static final long MR_QUALITY = 47836488L;
	public static final long MR_CONTAINER = 47836489L;
	public static final long MR_NEW_CONTAINER_NAME = 47836490L;
	public static final long MR_ACCOUNT_NUMBER = 47836491L;
	public static final long MR_CONTAINER_NO_PARENT = 47836492L;
	public static final long MR_BAD_MAIL_STRING = 47836493L;
	public static final long MR_NO_KRB4 = 47836494L;
	
	static {
		errMsgList = new Hashtable<Long, String>();
		errMsgList.put(MR_NOT_CONNECTED, "Not connected to Moira server");
		errMsgList.put(MR_CANT_CONNECT, "Can't connect to Moira server");
		errMsgList.put(MR_VERSION_MISMATCH, "Moira version mismatch");
		errMsgList.put(MR_ABORTED, "Moira operation aborted");
		errMsgList.put(MR_UNKNOWN_PROC, "Unknown procedure");
		errMsgList.put(MR_DBMS_ERR, "DBMS system error occurred");
		errMsgList.put(MR_MORE_DATA, "More data is available from Moira");
		errMsgList.put(MR_NO_MATCH, "No records in database match query");
		errMsgList.put(MR_NO_HANDLE, "Unknown query handle");
		errMsgList.put(MR_ALREADY_CONNECTED, "Already connected to the moira server");
		errMsgList.put(MR_ARGS, "Incorrect number of arguments");
		errMsgList.put(MR_NOT_UNIQUE, "Arguments not unique");
		errMsgList.put(MR_PERM, "Insufficient permission to perform requested database access");
		errMsgList.put(MR_LIST, "No such list");
		errMsgList.put(MR_USER, "No such user");
		errMsgList.put(MR_STRING, "Unknown string");
		errMsgList.put(MR_TYPE, "Invalid type");
		errMsgList.put(MR_EXISTS, "Record already exists");
		errMsgList.put(MR_DATE, "Invalid date");
		errMsgList.put(MR_CLUSTER, "Unknown cluster");
		errMsgList.put(MR_MACHINE, "Unknown machine");
		errMsgList.put(MR_SERVICE, "Unknown service");
		errMsgList.put(MR_FILESYS, "Named file system does not exist");
		errMsgList.put(MR_PRINTER, "Unknown printer");
		errMsgList.put(MR_QUEUE, "Unknown queue");
		errMsgList.put(MR_DEVICE, "No such device");
		errMsgList.put(MR_ACE, "No such access control entity");
		errMsgList.put(MR_NFSPHYS, "Machine/device pair not in nfsphys");
		errMsgList.put(MR_FILESYS_EXISTS, "Named file system already exists");
		errMsgList.put(MR_QUERY_NOT_REENTRANT, "Cannot do query from callback routine");
		errMsgList.put(MR_RVD, "No such rvd");
		errMsgList.put(MR_NFS, "Specified directory not exported");
		errMsgList.put(MR_FILESYS_ACCESS, "Invalid filesys access");
		errMsgList.put(MR_USER_GROUP, "List is a user group");
		errMsgList.put(MR_ARG_TOO_LONG, "An argument is too long");
		errMsgList.put(MR_NO_MEM, "Server ran out of memory");
		errMsgList.put(MR_IN_USE, "Object is in use");
		errMsgList.put(MR_BAD_CLASS, "Specified class is not known");
		errMsgList.put(MR_INTERNAL, "Moira internal consistency failure");
		errMsgList.put(MR_BAD_CHAR, "Illegal character in argument");
		errMsgList.put(MR_BAD_GROUP, "Invalid group ID");
		errMsgList.put(MR_WILDCARD, "Wildcards not allowed in this case");
		errMsgList.put(MR_NO_CHANGE, "The database has not changed, files not rebuilt");
		errMsgList.put(MR_TAR_FAIL, "Unable to build archive of config files");
		errMsgList.put(MR_OCONFIG, "Unable to open DCM file");
		errMsgList.put(MR_CCONFIG, "Error closing DCM output file");
		errMsgList.put(MR_FSTYPE, "Unknown filesys type");
		errMsgList.put(MR_INTEGER, "String could not be parsed as an integer");
		errMsgList.put(MR_NO_ID, "Cannot allocate new ID");
		errMsgList.put(MR_NO_FILESYS, "Cannot find space for filesys");
		errMsgList.put(MR_NO_POBOX, "Cannot find space for pobox");
		errMsgList.put(MR_NO_QUOTA, "No default quota specified");
		errMsgList.put(MR_USER_AUTH, "Cannot find you in the database, access will be restricted");
		errMsgList.put(MR_DEADLOCK, "Database deadlock; try again later");
		errMsgList.put(MR_NOCRED, "Unable to install new credentials files");
		errMsgList.put(MR_SETQUOTA, "Failure setting user quota");
		errMsgList.put(MR_HESFILE, "Unable to copy hesiod file into nameserver directory");
		errMsgList.put(MR_MISSINGFILE, "Did not receive file for update");
		errMsgList.put(MR_MKCRED, "unable to compile database files");
		errMsgList.put(MR_NAMED, "name daemon failed to start");
		errMsgList.put(MR_TARERR, "Unable to extract DCM files");
		errMsgList.put(MR_PROTO, "Failed to put prototype files in new locker");
		errMsgList.put(MR_BUSY, "the database is busy; try again later");
		errMsgList.put(MR_DOWN, "the database is closed right now; try again later");
		errMsgList.put(MR_LISTLOOP, "Lists are not allowed to contain themselves as members");
		errMsgList.put(MR_DBMS_SOFTFAIL, "Temporary database failure, try again");
		errMsgList.put(MR_COREDUMP, "Subprocess coredumped");
		errMsgList.put(MR_SUBNET, "Bad subnet");
		errMsgList.put(MR_ADDRESS, "Bad address");
		errMsgList.put(MR_VERSION_LOW, "Client query version is older than server");
		errMsgList.put(MR_VERSION_HIGH, "Client query version is newer than server");
		errMsgList.put(MR_RESERVED, "That name is reserved");
		errMsgList.put(MR_QUALITY, "Password is too simple");
		errMsgList.put(MR_CONTAINER, "No such container");
		errMsgList.put(MR_NEW_CONTAINER_NAME, "The new container name is invalid");
		errMsgList.put(MR_ACCOUNT_NUMBER, "No such account number");
		errMsgList.put(MR_CONTAINER_NO_PARENT, "Parent container does not exist");
		errMsgList.put(MR_BAD_MAIL_STRING, "Address refers to nonexistent domain or MIT internal mail server");
		errMsgList.put(MR_NO_KRB4, "Unable to complete operation using Kerberos v4");
	}
}
