package mit.moira.internal;

import java.util.Hashtable;

public class KrbET {
	private static Hashtable<Long, String> errMsgList;

	public static String getErrorMessage(long i) {
		return errMsgList.get(i);
	}

	public static final long KE_KSUCCESS = 39525376L;
	public static final long KE_KDC_NAME_EXP = 39525377L;
	public static final long KE_KDC_SERVICE_EXP = 39525378L;
	public static final long KE_KDC_AUTH_EXP = 39525379L;
	public static final long KE_KDC_PKT_VER = 39525380L;
	public static final long KE_KDC_P_MKEY_VER = 39525381L;
	public static final long KE_KDC_S_MKEY_VER = 39525382L;
	public static final long KE_KDC_BYTE_ORDER = 39525383L;
	public static final long KE_KDC_PR_UNKNOWN = 39525384L;
	public static final long KE_KDC_PR_N_UNIQUE = 39525385L;
	public static final long KE_KDC_NULL_KEY = 39525386L;
	public static final long KRB_RES11 = 39525387L;
	public static final long KRB_RES12 = 39525388L;
	public static final long KRB_RES13 = 39525389L;
	public static final long KRB_RES14 = 39525390L;
	public static final long KRB_RES15 = 39525391L;
	public static final long KRB_RES16 = 39525392L;
	public static final long KRB_RES17 = 39525393L;
	public static final long KRB_RES18 = 39525394L;
	public static final long KRB_RES19 = 39525395L;
	public static final long KE_KDC_GEN_ERR = 39525396L;
	public static final long KE_GC_TKFIL = 39525397L;
	public static final long KE_GC_NOTKT = 39525398L;
	public static final long KRB_RES23 = 39525399L;
	public static final long KRB_RES24 = 39525400L;
	public static final long KRB_RES25 = 39525401L;
	public static final long KE_MK_AP_TGTEXP = 39525402L;
	public static final long KRB_RES27 = 39525403L;
	public static final long KRB_RES28 = 39525404L;
	public static final long KRB_RES29 = 39525405L;
	public static final long KRB_RES30 = 39525406L;
	public static final long KE_RD_AP_UNDEC = 39525407L;
	public static final long KE_RD_AP_EXP = 39525408L;
	public static final long KE_RD_AP_NYV = 39525409L;
	public static final long KE_RD_AP_REPEAT = 39525410L;
	public static final long KE_RD_AP_NOT_US = 39525411L;
	public static final long KE_RD_AP_INCON = 39525412L;
	public static final long KE_RD_AP_TIME = 39525413L;
	public static final long KE_RD_AP_BADD = 39525414L;
	public static final long KE_RD_AP_VERSION = 39525415L;
	public static final long KE_RD_AP_MSG_TYPE = 39525416L;
	public static final long KE_RD_AP_MODIFIED = 39525417L;
	public static final long KE_RD_AP_ORDER = 39525418L;
	public static final long KE_RD_AP_UNAUTHOR = 39525419L;
	public static final long KRB_RES44 = 39525420L;
	public static final long KRB_RES45 = 39525421L;
	public static final long KRB_RES46 = 39525422L;
	public static final long KRB_RES47 = 39525423L;
	public static final long KRB_RES48 = 39525424L;
	public static final long KRB_RES49 = 39525425L;
	public static final long KRB_RES50 = 39525426L;
	public static final long KE_GT_PW_NULL = 39525427L;
	public static final long KE_GT_PW_BADPW = 39525428L;
	public static final long KE_GT_PW_PROT = 39525429L;
	public static final long KE_GT_PW_KDCERR = 39525430L;
	public static final long KE_GT_PW_NULLTKT = 39525431L;
	public static final long KE_SKDC_RETRY = 39525432L;
	public static final long KE_SKDC_CANT = 39525433L;
	public static final long KRB_RES58 = 39525434L;
	public static final long KRB_RES59 = 39525435L;
	public static final long KRB_RES60 = 39525436L;
	public static final long KE_INTK_W_NOTALL = 39525437L;
	public static final long KE_INTK_BADPW = 39525438L;
	public static final long KE_INTK_PROT = 39525439L;
	public static final long KRB_RES64 = 39525440L;
	public static final long KRB_RES65 = 39525441L;
	public static final long KRB_RES66 = 39525442L;
	public static final long KRB_RES67 = 39525443L;
	public static final long KRB_RES68 = 39525444L;
	public static final long KRB_RES69 = 39525445L;
	public static final long KE_INTK_ERR = 39525446L;
	public static final long KE_AD_NOTGT = 39525447L;
	public static final long KRB_RES72 = 39525448L;
	public static final long KRB_RES73 = 39525449L;
	public static final long KRB_RES74 = 39525450L;
	public static final long KRB_RES75 = 39525451L;
	public static final long KE_NO_TKT_FIL = 39525452L;
	public static final long KE_TKT_FIL_ACC = 39525453L;
	public static final long KE_TKT_FIL_LCK = 39525454L;
	public static final long KE_TKT_FIL_FMT = 39525455L;
	public static final long KE_TKT_FIL_INI = 39525456L;
	public static final long KE_KNAME_FMT = 39525457L;

	static {
		errMsgList = new Hashtable<Long, String>();
		errMsgList.put(KE_KSUCCESS, "Kerberos successful");
		errMsgList.put(KE_KDC_NAME_EXP, "Kerberos principal expired");
		errMsgList.put(KE_KDC_SERVICE_EXP, "Kerberos service expired");
		errMsgList.put(KE_KDC_AUTH_EXP, "Kerberos auth expired");
		errMsgList.put(KE_KDC_PKT_VER, "Incorrect kerberos master key version");
		errMsgList.put(KE_KDC_P_MKEY_VER, "Incorrect kerberos master key version");
		errMsgList.put(KE_KDC_S_MKEY_VER, "Incorrect kerberos master key version");
		errMsgList.put(KE_KDC_BYTE_ORDER, "Kerberos error: byte order unknown");
		errMsgList.put(KE_KDC_PR_UNKNOWN, "Kerberos principal unknown");
		errMsgList.put(KE_KDC_PR_N_UNIQUE, "Kerberos principal not unique");
		errMsgList.put(KE_KDC_NULL_KEY, "Kerberos principal has null key");
		errMsgList.put(KRB_RES11, "Reserved 11");
		errMsgList.put(KRB_RES12, "Reserved 12");
		errMsgList.put(KRB_RES13, "Reserved 13");
		errMsgList.put(KRB_RES14, "Reserved 14");
		errMsgList.put(KRB_RES15, "Reserved 15");
		errMsgList.put(KRB_RES16, "Reserved 16");
		errMsgList.put(KRB_RES17, "Reserved 17");
		errMsgList.put(KRB_RES18, "Reserved 18");
		errMsgList.put(KRB_RES19, "Reserved 19");
		errMsgList.put(KE_KDC_GEN_ERR, "Generic error from Kerberos KDC");
		errMsgList.put(KE_GC_TKFIL, "Can't read Kerberos ticket file");
		errMsgList.put(KE_GC_NOTKT, "Can't find Kerberos ticket or TGT");
		errMsgList.put(KRB_RES23, "Reserved 23");
		errMsgList.put(KRB_RES24, "Reserved 24");
		errMsgList.put(KRB_RES25, "Reserved 25");
		errMsgList.put(KE_MK_AP_TGTEXP, "Kerberos TGT Expired");
		errMsgList.put(KRB_RES27, "Reserved 27");
		errMsgList.put(KRB_RES28, "Reserved 28");
		errMsgList.put(KRB_RES29, "Reserved 29");
		errMsgList.put(KRB_RES30, "Reserved 30");
		errMsgList.put(KE_RD_AP_UNDEC, "Kerberos error: Can't decode authenticator");
		errMsgList.put(KE_RD_AP_EXP, "Kerberos ticket expired");
		errMsgList.put(KE_RD_AP_NYV, "Kerberos ticket not yet valid");
		errMsgList.put(KE_RD_AP_REPEAT, "Kerberos error: Repeated request");
		errMsgList.put(KE_RD_AP_NOT_US, "The kerberos ticket isn't for us");
		errMsgList.put(KE_RD_AP_INCON, "Kerberos request inconsistent");
		errMsgList.put(KE_RD_AP_TIME, "Kerberos error: delta_t too big");
		errMsgList.put(KE_RD_AP_BADD, "Kerberos error: incorrect net address");
		errMsgList.put(KE_RD_AP_VERSION, "Kerberos protocol version mismatch");
		errMsgList.put(KE_RD_AP_MSG_TYPE, "Kerberos error: invalid msg type");
		errMsgList.put(KE_RD_AP_MODIFIED, "Kerberos error: message stream modified");
		errMsgList.put(KE_RD_AP_ORDER, "Kerberos error: message out of order");
		errMsgList.put(KE_RD_AP_UNAUTHOR, "Kerberos error: unauthorized request");
		errMsgList.put(KRB_RES44, "Reserved 44");
		errMsgList.put(KRB_RES45, "Reserved 45");
		errMsgList.put(KRB_RES46, "Reserved 46");
		errMsgList.put(KRB_RES47, "Reserved 47");
		errMsgList.put(KRB_RES48, "Reserved 48");
		errMsgList.put(KRB_RES49, "Reserved 49");
		errMsgList.put(KRB_RES50, "Reserved 50");
		errMsgList.put(KE_GT_PW_NULL, "Kerberos error: current PW is null");
		errMsgList.put(KE_GT_PW_BADPW, "Kerberos error: Incorrect current password");
		errMsgList.put(KE_GT_PW_PROT, "Kerberos protocol error");
		errMsgList.put(KE_GT_PW_KDCERR, "Error returned by Kerberos KDC");
		errMsgList.put(KE_GT_PW_NULLTKT, "Null Kerberos ticket returned by KDC");
		errMsgList.put(KE_SKDC_RETRY, "Kerberos error: Retry count exceeded");
		errMsgList.put(KE_SKDC_CANT, "Kerberos error: Can't send request");
		errMsgList.put(KRB_RES58, "Reserved 58");
		errMsgList.put(KRB_RES59, "Reserved 59");
		errMsgList.put(KRB_RES60, "Reserved 60");
		errMsgList.put(KE_INTK_W_NOTALL, "Kerberos error: not all tickets returned");
		errMsgList.put(KE_INTK_BADPW, "Kerberos error: incorrect password");
		errMsgList.put(KE_INTK_PROT, "Kerberos error: Protocol Error");
		errMsgList.put(KRB_RES64, "Reserved 64");
		errMsgList.put(KRB_RES65, "Reserved 65");
		errMsgList.put(KRB_RES66, "Reserved 66");
		errMsgList.put(KRB_RES67, "Reserved 67");
		errMsgList.put(KRB_RES68, "Reserved 68");
		errMsgList.put(KRB_RES69, "Reserved 69");
		errMsgList.put(KE_INTK_ERR, "Other error");
		errMsgList.put(KE_AD_NOTGT, "Don't have Kerberos ticket-granting ticket");
		errMsgList.put(KRB_RES72, "Reserved 72");
		errMsgList.put(KRB_RES73, "Reserved 73");
		errMsgList.put(KRB_RES74, "Reserved 74");
		errMsgList.put(KRB_RES75, "Reserved 75");
		errMsgList.put(KE_NO_TKT_FIL, "No ticket file found");
		errMsgList.put(KE_TKT_FIL_ACC, "Couldn't access ticket file");
		errMsgList.put(KE_TKT_FIL_LCK, "Couldn't lock ticket file");
		errMsgList.put(KE_TKT_FIL_FMT, "Bad ticket file format");
		errMsgList.put(KE_TKT_FIL_INI, "tf_init not called first");
		errMsgList.put(KE_KNAME_FMT, "Bad Kerberos name format");
	}
}